Update Farming Specs with indexing
b-harvest/cosmos-sdk pull request #12
Opened 2021-07-14 05:38 UTC by dongsam

update spec with newly discussed design with indexing

2021-07-14 06:29 UTC, hallazzang requested changes

2021-07-14 06:29 UTC, hallazzang commented on x/farming/spec/02_state.md
> +- StakingByPlanIdIndex: `0x22 | PlanId -> Denom` or `0x22 | PlanId | Denom -> Id`
Why do we need `0x22 | PlanId -> Denom`(while there can be multiple denoms associated with a plan)?

2021-07-14 06:29 UTC, hallazzang commented on x/farming/spec/02_state.md
> +- StakingPositionByStakingIdIndex: `0x33 | stakingId | -> Id`
I think we don't need the last index, `0x33 | stakingId -> Id` since multile `StakingPosition`s can be associated with `Staking`

2021-07-14 06:29 UTC, hallazzang commented on x/farming/spec/03_state_transitions.md
> +- New `Staking` objects are created when new `Plan` is created, with each `StakingCoinDenom` in the new `Plan`.
`StakingCoinDenom` -> `Denom`

2021-07-14 06:29 UTC, hallazzang commented on x/farming/spec/04_messages.md
> +    StakingId                uint64
We should `gofmt` the file, since the PR uses 4 spaces instead of a tab character.

2021-07-14 06:29 UTC, hallazzang commented on x/farming/spec/08_params.md
> +| ----------------------      | --------- | ---------------------------------------- |
need more `-`

2021-07-14 07:01 UTC, dongsam commented on x/farming/spec/02_state.md
> +- StakingPositionByStakingIdIndex: `0x33 | stakingId | -> Id`
`StakingPositionByStakingIdIndex` is indexing iterable `id`s by `stakingId` I just updated the expression.

2021-07-14 07:02 UTC, dongsam commented on x/farming/spec/02_state.md
> +- StakingByPlanIdIndex: `0x22 | PlanId -> Denom` or `0x22 | PlanId | Denom -> Id`
Yes It is indexing iterable `denom`s I think it need to query quickly and `Staking` table size is small but often used.

2021-07-14 07:44 UTC, dlguddus commented on x/farming/spec/03_state_transitions.md
> +- New `Staking` objects are created when new `Plan` is created, with each `StakingCoinDenom` in the new `Plan`.
i would rather suggest kinder naming because it is unclear which token's denom it is.
`StakingCoinDenom` clearly define the identity of the denom.

2021-07-15 01:29 UTC, dongsam commented on x/farming/spec/04_messages.md
> -	Farmer string
All msgs need to msg sender address ( in this case farmer) for verifying the signature of the msg using the `msg.sender`'s address,  So I think it's better to use `Farmer` than `StakingPositionId`.

And it can be tricky for users to find and enter a `StaingId` to claim the reward. Instead of specifying the `StaingId`, we can consider giving only the option of claim all rewards at once. Or inputting `stakingCoinDenom` is another option.

@dlguddus @hallazzang @kogisin

2021-07-16 05:53 UTC, dongsam commented
Although there are parts that are not fully implemented and that are left as TODO, we first merge them for repo migration.

2021-07-16 05:53 UTC, merged