V0.45.16 send restriction
b-harvest/cosmos-sdk pull request #173
Opened 2024-09-04 10:05 UTC by poorphd

# Description

This PR enables send restriction when initialize `BankKeeper`

Closes: #XXXX

---

## Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

* [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title, you can find examples of the prefixes below:
    
* [ ] confirmed `!` in the type prefix if API or client breaking change
* [ ] targeted the correct branch (see [PR Targeting](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#pr-targeting))
* [ ] provided a link to the relevant issue or specification
* [ ] reviewed "Files changed" and left comments if necessary
* [ ] included the necessary unit and integration [tests](https://github.com/cosmos/cosmos-sdk/blob/main/CONTRIBUTING.md#testing)
* [ ] added a changelog entry to `CHANGELOG.md`
* [ ] updated the relevant documentation or specification, including comments for [documenting Go code](https://blog.golang.org/godoc)
* [ ] confirmed all CI checks have passed

## Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

Please see [Pull Request Reviewer section in the contributing guide](../CONTRIBUTING.md#reviewer) for more information on how to review a pull request.

I have...

* [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
* [ ] confirmed all author checklist items have been addressed
* [ ] reviewed state machine logic, API design and naming, documentation is accurate, tests and test coverage

2024-09-09 02:28 UTC, dongsam requested changes

2024-09-09 02:28 UTC, dongsam commented on x/bank/keeper/send.go
> +		for _, in := range inputs {
This could be inefficient with a nested for-loop. If the checks for the from and to addresses in sendCoinsRestrictionFn are independent, wouldn't it be possible to simplify it into a one-dimensional check by validating only the from address for inputs and only the to address for outputs?

(need to check if it is possible to handle an empty "from" or "to" address without errors, and add unit tests accordingly)

2024-09-09 02:28 UTC, dongsam commented on x/bank/keeper/keeper.go
> +	oldRestrictionFn := k.sendCoinsRestrictionFn
- Consider whether oldRestrictionFn could still be used since it is pre-assigned.
- If so, add test cases to check if multiple RestrictionFn are redundantly processed when WithSendCoinsRestriction is nested multiple times.

2024-09-09 02:57 UTC, zsystm reviewed
@poorphd 
I have left comments only for test code. 
Core logics look great to me.

2024-09-09 02:57 UTC, zsystm commented on x/bank/keeper/keeper_test.go
> +	blockedAddr := sdk.AccAddress([]byte("blockedaddr---------"))
Type conversion isn't necessary. The following code also works.
```suggestion
	normalAddr1 := sdk.AccAddress("addr1---------------")
	normalAddr2 := sdk.AccAddress("addr2---------------")
	blockedAddr := sdk.AccAddress("blockedaddr---------")
```

2024-09-09 02:57 UTC, zsystm commented on x/bank/keeper/keeper_test.go
> +	}
How about using `expectedError string` instead of `expectPass bool`? 
So we can know the details of error and find where the error occurred exactly.

ref. https://github.com/zsystm/story/blob/6b72ab9151a0b872b58684b113e813fac8c15d51/client/x/evmstaking/keeper/validator_test.go#L56-L77

2024-09-09 02:57 UTC, zsystm commented on x/bank/keeper/keeper_test.go
> +		},
I’m a little confused about what this test case is trying to test. 
The test is related to send restrictions, not mint restrictions.

2024-09-09 02:57 UTC, zsystm commented on x/bank/keeper/keeper_test.go
> +	)
This setup should only be included in the setup function for the specific test case.
e.g.
```
	tests := []struct {
		name          string
                setup func(ctx context.Context)
		restrictionFn BankSendRestrictionFn
		testCases     []testCase
	}{
		{
	            setup: func(ctx context.Context) {suite.Require().NoError(
		            suite.app.BankKeeper.MintCoins(
			            ctx,
			            "newbankmodule",
			            sdk.NewCoins(coin)),
	            )
```

2024-09-09 02:58 UTC, zsystm commented
@poorphd 
+ Please fix the CI error also.

2024-09-09 09:56 UTC, poorphd commented on x/bank/keeper/send.go
> +		for _, in := range inputs {
Due to the bypass functionality for module accounts, it is deemed difficult to independently assess input addresses and output addresses.
However, an incorrect logic has been discovered in the current code where the restriction application is determined after subUnlockedCoins, so I will modify that part.

2024-09-09 13:31 UTC, poorphd commented on x/bank/keeper/send.go
> +		for _, in := range inputs {
Due to the bypass functionality for module accounts, it is deemed difficult to independently assess input addresses and output addresses.
However, an incorrect logic has been discovered in the current code where the restriction application is determined after subUnlockedCoins, so I will modify that part.

2024-09-09 13:42 UTC, poorphd commented on x/bank/keeper/keeper.go
> +	oldRestrictionFn := k.sendCoinsRestrictionFn
test code for nested restriction functions are added in https://github.com/b-harvest/cosmos-sdk/pull/173/commits/e7a3104a5ec40864b98ec22a164be99d8c327ae2

2024-09-09 13:45 UTC, poorphd commented on x/bank/keeper/keeper_test.go
> +	blockedAddr := sdk.AccAddress([]byte("blockedaddr---------"))
This part was written following the existing Cosmos SDK test code convention. In the new test code added for this PR,  I have removed all byte conversions but not existing tests. https://github.com/b-harvest/cosmos-sdk/pull/173/commits/deb55d353d75998ab7451b449c17af3bb1bea2de

2024-09-09 13:46 UTC, poorphd commented on x/bank/keeper/keeper_test.go
> +	}
suggestion applied for every functions added for this PR. https://github.com/b-harvest/cosmos-sdk/pull/173/commits/02875230b789db9238e2d30bdb01e3ca1785889b

2024-09-09 13:51 UTC, poorphd commented on x/bank/keeper/keeper_test.go
> +		},
Minting and burning were terms used in noble-usdy, which we referenced to implement send restrictions, meaning the transfer from a module account to a regular account and vice versa. To eliminate confusion, I have changed them to "send coins to module account" and "receive coins from module account" respectively.

2024-09-09 13:52 UTC, poorphd commented on x/bank/keeper/keeper_test.go
> +	)
suggestion is applied in https://github.com/b-harvest/cosmos-sdk/pull/173/commits/02875230b789db9238e2d30bdb01e3ca1785889b

2024-09-10 01:36 UTC, poorphd commented
> @poorphd
> 
> * Please fix the CI error also.

The existing codebase had broken CI. This should be fixed in a separate PR.

2024-09-10 01:54 UTC, zsystm approved these changes
LGTM

2024-09-10 13:12 UTC, dongsam commented
I remember hearing that in the previous localnet end-to-end test, even when restrictions occurred, errors were not exposed. Do you know if that issue has been resolved? Regardless of whether it's been fixed, it would be ideal if the test code could verify the occurrence of errors.

2024-09-11 03:19 UTC, poorphd commented
> I remember hearing that in the previous localnet end-to-end test, even when restrictions occurred, errors were not exposed. Do you know if that issue has been resolved? Regardless of whether it's been fixed, it would be ideal if the test code could verify the occurrence of errors.

The issue is resolved. If the transaction failed due to the restriction, the raw_log contains the error message. 
Latest test codes already check expected errors. https://github.com/b-harvest/cosmos-sdk/blob/v0.45.16/SendRestiction/x/bank/keeper/keeper_test.go#L1273-L1277

2024-09-11 03:45 UTC, dongsam approved these changes

2024-09-11 03:49 UTC, merged

2024-09-25 06:20 UTC, cloudgray commented on x/bank/keeper/send.go
> +		for _, in := range inputs {
[Optional] According to [arguments validation logic](https://github.com/b-harvest/cosmos-sdk/blob/eaa582a6d9d34eacaba1d042bae8b1e659ed95b1/x/bank/types/msgs.go#L166-L193), input[i] is send to output[i], not output[j]. so, nested for-loop can be modified to single for-loop.
```
// Apply restriction check between input and all outputs before subtracting coins
outAddress, err := sdk.AccAddressFromBech32(outputs[i].Address)
if err != nil {
	return err
}

// TODO: applying restriction check based on input and output coin amount
// Check restrictions between the input address and the output address
outAddress, err = k.sendCoinsRestrictionFn(ctx, inAddress, outAddress, outputs[i].Coins)
if err != nil {
	return err
}
```

2024-09-25 06:31 UTC, cloudgray commented on x/bank/keeper/keeper_test.go
> +	type BankSendRestrictionFn func(ctx sdk.Context, fromAddr, toAddr sdk.AccAddress, amt sdk.Coins) (sdk.AccAddress, error)
[Suggestion] How about using existing [`type SendRestrictionFn` in keeper.go](https://github.com/b-harvest/cosmos-sdk/blob/eaa582a6d9d34eacaba1d042bae8b1e659ed95b1/x/bank/keeper/keeper.go#L62)

Is there any reason to define same type in test code?

2024-09-25 07:02 UTC, cloudgray commented on x/bank/keeper/send.go
> +			outAddress, err = k.sendCoinsRestrictionFn(ctx, inAddress, outAddress, out.Coins)
[Suggestion] How about seperate `SendFromRestrictionFn` and `SendToRestrictionFn` ?
Considering [InputOutputCoins](https://github.com/b-harvest/cosmos-sdk/blob/eaa582a6d9d34eacaba1d042bae8b1e659ed95b1/x/bank/keeper/send.go#L79-L154), it looks better logic to apply "from restriction" and "to restriction".

In minting case, it is better to use existing [MintingRestrictionFn](https://github.com/b-harvest/cosmos-sdk/blob/v0.45.16%2FSendRestiction/x/bank/keeper/keeper.go#L57).

In burning case, it is allowed regardless of `from` or `to`.

If it is required to block a specific sender from sending to a specific receiver, I thnik that restriction function should not be applied to the InputOutputCoins function.